module "app_pattern" {
    source                = "./terraform_standard_application_module"
    environment           = "${var.environment}"
    location              = "${var.location}"
    division              = "${var.business_unit}"
    cost_center           = "${var.cost_center}"
    requestor             = "${var.requestor}"
    confidentiality_input = "${var.confidentiality}"
    accessibility_input   = "${var.accessibility}"
    criticality_input     = "${var.criticality}"
    appid                 = "${var.appid}"
    audit_input           = "${var.audit}"
    expiration_date       = "${var.expiration_date}"
    virtual_network       = "${var.virtual_network}"
    virtual_network_rg    = "${var.virtual_network_rg}"
    subnet_prefix         = "${var.subnet_prefix}"
    resource_group_name   = "${module.app_rg.concatenated_name}"
    subnet_name           = "${module.app_sn.concatenated_name}"
    nsg_name              = "${module.app_nsg.concatenated_name}"
    recovery_vault_name   = "${module.app_rsv.concatenated_name}"
    storage_account_name  = "${module.app_sa.lower_name_rand}"
    sub_id                = "${var.azure_sub_id}"
    rt_id                 = "${var.rt_id}"
}
#Shared SQL VM
module "app_ipconfig01" {
    source                    = "./terraform_naming_module"
    resource_type_input       = "ip_config"
    business_unit_input       = "${var.business_unit}"
    workload                  = "${var.vmName01}"
    environment_input         = "${var.environment}"
    location_descriptor_input = "${var.location}"
}
module "app_nic01" {
    source                    = "./terraform_naming_module"
    resource_type_input       = "network_interface"
    business_unit_input       = "${var.business_unit}"
    workload                  = "${var.vmName01}"
    environment_input         = "${var.environment}"
    location_descriptor_input = "${var.location}"
}
module "app_vmdisk01" {
    source                    = "./terraform_naming_module"
    resource_type_input       = "disk"
    business_unit_input       = "${var.business_unit}"
    workload                  = "${var.vmName01}"
    environment_input         = "${var.environment}"
    location_descriptor_input = "${var.location}"
}

module "virtual_machines" {
    source                       = "./terraform_sqlvm_azure_module"
    azLocation                   = "${var.location}"
    countInt                     = "${var.countInt}"
    ipConfigurationPrependName   = "${module.app_ipconfig01.loop_prepend}"
    ipConfigurationAppendName    = "${module.app_ipconfig01.loop_append}"
    nicPrependName               = "${module.app_nic01.loop_prepend}"
    nicAppendName                = "${module.app_nic01.loop_append}"
    privateIPAddressStart        = "${var.privateIPAddressStart01}"
    rgName                       = "${module.app_pattern.rg_name}"
    subnetId                     = "${module.app_pattern.sn_id}"
    OSProfileComputerPrependName = "${var.vmName01}"
    OSProfileComputerAppendName  = "${var.vmEnv}"
    virtualMachineSize           = "${var.virtualMachineSize}"
    vmDiskPrependName            = "${module.app_vmdisk01.loop_prepend}"
    vmDiskAppendName             = "${module.app_vmdisk01.loop_append}"
    vmPrependName                = "${var.vmName01}"
    vmAppendName                 = "${var.vmEnv}"
    availabilitySetId            = "${azurerm_availability_set.application.id}"
    sa_blob_endpoint             = "${module.app_pattern.sa_blob_endpoint}"
    sa_blob_access_key           = "${module.app_pattern.sa_primary_access_key}"
    WindowsStorageImageReferencePublisher = "${var.sqlpublisher}"
    WindowsStorageImageReferenceOffer = "${var.sqloffer}"
    WindowsStorageImageReferenceSKU = "${var.sqlsku}"
    WindowsStorageImageReferenceVersion = "${var.sqlversion}"
}

